/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/flow/FlowEventUtil.p.vm.java
 */
package ca.rsagroup.web.flow;

import javax.faces.context.FacesContext;
import javax.inject.Named;

import org.springframework.faces.webflow.JsfView;

@Named
public class FlowEventUtil {
    public void event(String eventId) {
        FacesContext.getCurrentInstance().getExternalContext().getRequestMap().put(JsfView.EVENT_KEY, eventId);
    }

    public void select() {
        event("select");
    }

    public void edit() {
        event("edit");
    }
}
