/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/util/LocaleUtil.p.vm.java
 */
package ca.rsagroup.web.util;

import static org.apache.commons.lang.StringUtils.isBlank;

import java.util.Map;

import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;

import org.springframework.web.servlet.i18n.LocaleChangeInterceptor;

@Named
public class LocaleUtil {

    /**
     * This local parameter can be changed in the configuration. Please make sure it is in sync.
     */
    private static final String LOCALE_PARAMETER_NAME = LocaleChangeInterceptor.DEFAULT_PARAM_NAME;

    public String addLocale(HttpServletRequest request, String languageToChange) {
        @SuppressWarnings("unchecked")
        Map<String, String[]> params = request.getParameterMap();

        StringBuilder url = new StringBuilder(512);
        url.append(request.getRequestURL().toString()).append('?');
        for (String key : params.keySet()) {
            if (!LOCALE_PARAMETER_NAME.equals(key)) {
                String value = request.getParameter(key);
                url.append(key).append('=');
                if (!isBlank(value)) {
                    url.append(value);
                }
                url.append('&');
            }
        }
        url.append(LOCALE_PARAMETER_NAME).append('=').append(languageToChange);
        return url.toString();
    }
}